// src/services/commandService.ts
import apiClient from "./apiClient";
import type {
  CommandResponse,
  RequestScreenCapturePayload,
  PerformActionPayload,
} from "@/types/api";

export const commandService = {
  async sendCaptureScreenCommand(
    deviceId: string,
    params?: Partial<RequestScreenCapturePayload> // Make params optional or provide defaults
  ): Promise<CommandResponse> {
    const payload: RequestScreenCapturePayload = {
      correlationId: params?.correlationId, // Allow UI to pass one if needed
      format: params?.format || "jpeg",
      quality: params?.quality || 80,
      maxWidth: params?.maxWidth,
    };
    return apiClient.post(
      `/devices/${deviceId}/command/capture_screen`,
      payload
    );
  },

  async sendUiStructureCommand(deviceId: string): Promise<CommandResponse> {
    // This command might not need a request body if correlationId is generated by backend for this specific API call
    // Or, if it needs one (e.g. for a correlationId from UI):
    // return apiClient.post(`/devices/${deviceId}/command/ui_structure`, { correlationId: generateUUID() });
    return apiClient.post(`/devices/${deviceId}/command/ui_structure`);
  },

  async sendPerformActionCommand(
    deviceId: string,
    payload: PerformActionPayload
  ): Promise<CommandResponse> {
    return apiClient.post(
      `/devices/${deviceId}/command/perform_action`,
      payload
    );
  },
};
