// src/services/commandService.ts
import apiClient from "./apiClient";
import type {
  CommandResponse,
  RequestScreenCapturePayload,
  PerformActionPayload,
} from "@/types/api";
import { v4 as uuidv4 } from "uuid";

export const commandService = {
  async sendCaptureScreenCommand(
    deviceId: string,
    params?: Partial<RequestScreenCapturePayload> // Make params optional or provide defaults
  ): Promise<CommandResponse> {
    const payload: RequestScreenCapturePayload = {
      // 如果调用者没有提供 correlationId，就生成一个新的 UUID
      correlationId: params?.correlationId || uuidv4(),
      format: params?.format || "jpeg",
      quality: params?.quality || 80,
      maxWidth: params?.maxWidth,
    };
    return apiClient.post(
      `/devices/${deviceId}/command/capture_screen`,
      payload
    );
  },

  async sendUiStructureCommand(deviceId: string): Promise<CommandResponse> {
    // This command might not need a request body if correlationId is generated by backend for this specific API call
    // Or, if it needs one (e.g. for a correlationId from UI):
    // return apiClient.post(`/devices/${deviceId}/command/ui_structure`, { correlationId: generateUUID() });
    return apiClient.post(`/devices/${deviceId}/command/ui_structure`, {
      // 同样为这个请求也加上ID，保持一致性
      correlationId: uuidv4(),
    });
  },

  async sendPerformActionCommand(
    deviceId: string,
    payload: PerformActionPayload
  ): Promise<CommandResponse> {
    // 确保这个 payload 也有 ID
    if (!payload.correlationId) {
      payload.correlationId = uuidv4();
    }
    return apiClient.post(
      `/devices/${deviceId}/command/perform_action`,
      payload
    );
  },
};
